config/routes.rb
AdventureStore::Application.routes.draw do
 root :to => 'adventures#index'
  devise_for :users
  resources :adventures do
    member do
      get 'purchase'
    end
  resources :reviews, only: [:new, :create]
  end

end

app/models/adventure.rb
class Adventure < ActiveRecord::Base
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  has_many :reviews
  has_and_belongs_to_many :users
  has_attached_file :photo, :styles => { :medium => "300x300", :thumb => "100x100"}
   validates_attachment_content_type :photo,
                                    :content_type => /^image\/(png|gif|jpeg)/,
                                    :message => 'only (png/gif/jpeg) images'

  def self.search_model(target_state,target_category)
    # the blank selection is set to 'false' in the select menue. Cannot pass booleans through params
    if target_state != 'false' && target_category == 'false'
      where('state = ?', target_state)
    elsif target_category != 'false' && target_state == 'false'
      where('category = ?', target_category)
    elsif target_state != 'false' && target_category != 'false'
      where('state = ? AND category = ?', target_state, target_category)
    else
      scoped
    end
    # if target_state && target_category
    #   where('state = ? AND category = ?', target_state, target_category)
    # elsif target_state
    #   where('state = ?', target_state)
    # elsif target_category
    #   where('category = ?', target_category)
    # else
    #   scoped
    # end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :adventure
  belongs_to :user
  validates :comment, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  has_and_belongs_to_many :adventures
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/adventures_controller.rb
class AdventuresController < ApplicationController
  def index

    if params[:search_states] && params[:search_category]
    @adventures = Adventure.search_model(params[:search_states,], params[:search_category]).paginate(:page => params[:page], :per_page => 5)
    else
      @adventures = Adventure.all.paginate(:page => params[:page], :per_page => 5)
    end
  end
  def show
    @review = Review.new

    @adventure = Adventure.find(params[:id])
  end
  def new
    @adventure = Adventure.new
  end

  def create
    @adventure = Adventure.new(adventure_params)
    if @adventure.save
      redirect_to adventure_path(@adventure)
    else
      render :new
    end
  end

  def edit
    @adventure = Adventure.find(params[:id])
  end

  def update
    @adventure = Adventure.find(params[:id])
    if @adventure.update(adventure_params)
      redirect_to adventure_path(@adventure)
    else
      render :edit
    end
  end
  def destroy
    @adventure = Adventure.find(params[:id])
    @adventure.destroy
    redirect_to :action => :index
  end
  def purchase
    @adventure = Adventure.find(params[:id])
    @adventure.users << current_user
  end
  private
  def adventure_params
    params.require(:adventure).permit(:title, :description, :state, :category, :price, :photo)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @adventure = Adventure.find(params[:adventure_id])
  end
  def create
    @review = Review.new(review_params)
    @user = current_user
    @adventure = Adventure.find(params[:adventure_id])
    if @review.save
      @user.reviews << @review
      @adventure.reviews << @review
      respond_to do |format|
        format.html { redirect_to adventure_path(@adventure) }
        format.js
      end
    else
      respond_to do |format|
        format.html { redirect_to adventure_path(@adventure)}
        format.js { render 'new' }
      end
    end
  end

  private
  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def stars
    [
      ["*", 1],
      ["**", 2],
      ["***", 3],
      ["****", 4],
      ["*****", 5]
    ]
  end
  def adventure_categories
    [
      ['Any Category', 'false'],
      ['Climbing'],
      ['Hiking'],
      ['Swimming'],
      ['Rafting'],
      ['Skiing, Alpine'],
      ['Skiing, Backcountry'],
      ['Snowboarding'],
      ['Yoga'],
      ['Biking, Road'],
      ['Biking, Mountain'],
      ['Splunking'],
      ['Paragliding'],
      ['Sky Diving'],
      ['Kite Surfing'],
      ['Surfing'],
      ['Other']


    ]
  end

  def us_states
   [
    ['Any State', 'false'],
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Puerto Rico', 'PR'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']

  ]

end
end

app/views/adventures/_form.html.erb
<%= render "layouts/errors", :object => @adventure %>

<%= form_for @adventure, :html => { :multipart => true } do |f| %>
  <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, :class => "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, :size => "60x12", :class => "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :price %>
  <%= f.number_field :price, :step => 'any' %>
  </div>
  <div class="form-group">
  <%= f.select :state, us_states %>
  <%= f.select :category, adventure_categories %>
  </div>
  <div class="form-group file-upload">
  <%= f.file_field :photo %>
  </div>
  <%= f.submit :class => "btn btn-info" %>
<% end %>

app/views/adventures/edit.html.erb
<%= render('form') %>

app/views/adventures/index.html.erb
<h1>GO ADVENTURE</h1>
<hr>
<div class="row search_fields">
  <%= form_tag adventures_path, :method => 'get' do %>
    <%= select_tag :search_states, options_for_select(us_states) %>
    <%= select_tag :search_category, options_for_select(adventure_categories) %>
    <%= submit_tag "Search", :name => nil, :class => "btn btn-info pull-right" %>
  <% end %>
</div>
<hr>
<div class="row">
 <% @adventures.each do |adventure| %>
    <div class="panel panel-dfault">
      <div class="panel-heading">
        <h3 class="panel-title"><%= link_to adventure.title, adventure_path(adventure) %></h3>
      </div>
      <div class="panel-body">
        <div class="col-sm-10">
          <p><%= adventure.description %></p>
        </div>
        <div class="col-sm-2">
          <p><%= image_tag adventure.photo.url(:thumb)%></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

<% if current_user %>
  <%= link_to "Add A New Adventure", new_adventure_path, :class => "bnt btn-info" %>
<% end %>

<div class="row pull-right">
<%= will_paginate @adventures %>
</div>

app/views/adventures/new.html.erb
<%= render('form') %>

app/views/adventures/purchase.html.erb
<h1>Thank Your for Your Purchase</h1>

<h3>Now This is Going to Take a Bit of Imagination</h3>

<p>since this is a mock web-app the adventure you bought doesn't exactly exist...but that doesn't mean that you cannot go on a wonderful imaginary adventure. So we give you permission to spend the next five minutes quietly contemplating the adventure you just 'purchased'. What do you think the air would smell like? Imagine the texture of the soil? Feel the breeze gently brush against your face. Feel the warmth of the sun accross your face. Inhale, Exhale. </p>

<%= link_to "I'm Done Playing Imaginary Games", root_path, :class => 'btn btn-warning'  %>

app/views/adventures/show.html.erb
<h1><%= @adventure.title %><h1>
<div class="row">
  <div class="col-md-8">
  <p class="description"><%= @adventure.description %></p>
  <p class = "pull-left">Only $<%= @adventure.price %>!</p>
  </div>
  <div class="col-md-4">
    <p><%= image_tag @adventure.photo.url(:medium) %></p>
  </div>
</div>

<hr>
<h2>Reviews</h2>
<div class="row">
  <div class="col-md-10">
    <ul id="show-reviews">
      <% if @adventure.reviews %>
        <% @adventure.reviews.each do |review| %>
          <li><%= review.comment %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="col-md-2">
    <% if current_user %>
      <%= link_to "Add Review", new_adventure_review_path(@adventure), :remote => true, :id => "new_review", :class => "btn btn-info"  %>
      <%= link_to "Go On Adventure", purchase_adventure_path(@adventure), :class => 'btn btn-primary'%>
    <% end %>
  </div>
</div>

<% if current_user %>
  <nav class="navbar navbar-fixed-bottom center" role="navigation">
    <div class="navbar-inner">
      <%= link_to "Edit Adventure", edit_adventure_path(@adventure), :class => "navbar-text pull-right"%>
      <%= link_to "Delete Adventure", adventure_path(@adventure), data: { confirm: "are you sure?", method: "delete" }, :class => 'navbar-text pull-right'%>
    </div>
  </nav>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <%end%>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdventureStore</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <nav class="nav navbar-inverse" role="navigation">
    <span class="logo navbar-brand"><%= link_to "Adventure Store", root_path %></span>

      <% if current_user.nil? %>
        <%= link_to "Login" ,new_user_session_path, class: "navbar-text pull-right" %>
        <%= link_to "Signup ", new_user_registration_path, class: "navbar-text pull-right" %>
      <% else %>
        <%= link_to "Signout", destroy_user_session_path, method: 'delete', class: "navbar-text pull-right" %>
      <% end %>

  </nav>
 <div class="container">
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= yield %>
 </div>
</body>
</html>

app/views/reviews/_new.html.erb
<%= render('layouts/errors', :object => @review ) %>

<div id="new_review_form">
  <%= form_for [@adventure, @review], :remote => true do |f| %>
    <div class="form-group">
      <%= f.select :rating, stars %>
    </div>
    <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, :size => "60x12", :class => "form-control" %>
    </div>
    <%= f.submit :class => "btn btn-info" %>
  <% end %>
</div>

app/views/reviews/create.js.erb
$('#new_review_form').remove();
$('.error_messages').remove();
$('#new_review').show();
$('#show-reviews').append('<li><%= @review.comment %></li>')

app/views/reviews/new.js.erb
$('#new_review_form').remove()

$('#new_review').hide().after('<%= j render("new") %>');